### PR TITLE
Remove duplicated example

### PR DESCRIPTION
**Pull request by stappersg**
one set of

if sys.version_info >= (3,):
    print('python3!')

will do    :-)

### CODE REVIEW

**Comment by asottile** [comment]
there are N wrong examples and then N replacements for those N wrong examples

**Comment by stappersg** [comment]
> there are N wrong examples and then N replacements for those N wrong examples

Now I know. Thanks for telling.

I feel the need to share that information with the README.md.
Another merge request is work in progress.

**Comment by asottile** [comment]
please don't, thanks

**Comment by stappersg** [comment]
> please don't, thanks

#100 was created before I did see that request ...

**Pull request closed without merging**
